### Index method
GET http://localhost:3000/api/fitnices

### Successfully made a a extra workout

POST http://localhost:3000/api/fitnices
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NTkxNjQ4NzQsInN1YiI6MX0.fmldAwzW-wj27EF05pikf30tUL0xxgh-l2Gk-1XyT_c

{  
    "exercise_id": 1,
    "targetmusclecategory_id": 3,
    "category_id": 1,
    "body": "selected quadriceps and FitNice"
}

### Unsuccesfully made a extra workout 

POST http://localhost:3000/api/fitnices
Content-Type: application/json

{
    "body": "Selected arm workout"
}

### Show fitnice id:1 

GET http://localhost:3000/api/fitnices/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NTg1Mzg2NzQsInN1YiI6M30.UuYJQHbVjQQ6wwunMQqfLafXmkiDUlvQ-kjw5jZ0k94

### Unsuccesfully show fitnice by id

GET http://localhost:3000/api/fitnices/112312

### Sucessfully update fitnice workout id of 3

PUT http://localhost:3000/api/fitnices/5
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NTkxNTYxNDksInN1YiI6M30.ohlx948HJ4wOhCZPRM841mMM1Qv-JoZ8Uipfeau7mEk

{
    "targetmuscle_id": 1,
    "category_id": 2,
    "body": "Leg workout"
}

### Successfully delete fitnice workout with id of 1 

DELETE http://localhost:3000/api/fitnices/1

### Unsuccesfully delete fitnice workout by id

DELETE http://localhost:3000/api/fitnices/112312

### Destroy joke i have permissions for 
DELETE http://localhost:3000/api/fitnices/3
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NTg1Mzg2NzQsInN1YiI6M30.UuYJQHbVjQQ6wwunMQqfLafXmkiDUlvQ-kjw5jZ0k94


### Succesfully create User

POST http://localhost:3000/api/auth/sign_up
Content-Type: application/json

{
    "username": "ET",
    "email": "ET@gmail.com",
    "password": "password",
    "password_confirmation": "password"
}

### Sign in with correct details

POST http://localhost:3000/api/auth/sign_in
Content-Type: application/json

{
    "email": "ET@gmail.com",
    "password": "password"
}
### Sign in with incorrect details

POST http://localhost:3000/api/auth/sign_in
Content-Type: application/json

{
    "email": "eric2@gmail.com",
    "password": "pass4"
}

# Get categories 

GET http://localhost:3000/api/categories
Content-Type: application/json

#Get Target muscles

GET http://localhost:3000/api/targetmuscles
Content-Type: application/json
















